### ISSUE TITLE
Assertion failure

### ISSUE THREAD

**Issue by TOTHT0MI** [natanbc/lavadsp#52]
This is like the 20th time the native library throws an assertion error at me, when speed is changed, with the timescale.
Here's an image of the error:
https://prnt.sc/t7juzw

**Comment by alula** [comment]
The library version there is quite outdated, have you checked upstream SoundTouch test apps?

**Comment by TOTHT0MI** [comment]
Nah, I don't think so, I'm not really familiar with SoundTouch nor with C++
