### ISSUE TITLE
Natives Issue

### ISSUE THREAD

**Issue by MeLike2D** [natanbc/lavadsp#56]
Hello! There's an issue with version `0.7.2`, [here are logs](https://hasteb.in/husasoqi.swift) from using lavadsp `0.7.2`.
When using `0.7.1` this error does not occur and the timescale filter works perfectly fine. The systems that these errors have occurred on are different... the logs I sent are from an Ubuntu system from [oxide.host](https://oxide.host) and my vps is running debian 10 and it's from contabo. 

I'll be glad to share any information if it's needed

**Comment by MeLike2D** [comment]
Oh and this worked perfectly fine on my machine (manjaro linux, intel system)

**Comment by natanbc** [comment]
[This](https://github.com/wheybags/glibc_version_header) might be an option, for now the docker image should work

**Comment by natanbc** [comment]
Fixed in [0.7.3](https://github.com/natanbc/lavadsp/releases/tag/0.7.3)
