### ISSUE TITLE
Vibrato effect barely noticable

### ISSUE THREAD

**Issue by DaliborTrampota** [natanbc/lavadsp#71]
Hello, I own a discord bot which is running on lavalink. I've implemented filters from lavadsp myself, running on latest 0.7.6 lavadsp and the filters are really weak and barely noticeable. Is there a way to crank it up a bit more? For the filter to be atleast a bit noticeable you need to have depth at 1 which is the max. I dont know how it all works but maybe increate how much it oscilates when at 1 or allow for higher value than 1? It really makes me think about ffmpeg because there is so many filters. I know its different but why it cant be like it?

**Comment by arararat** [comment]
Can you tell which filters are there ?

**Comment by DaliborTrampota** [comment]
Dead. closing.
