### ISSUE TITLE
Applying lowpass and timescale causes the track to break.

### ISSUE THREAD

**Issue by TopiSenpai** [natanbc/lavadsp#81]
Applying lowpass with timescale causes the track to break, with the following error Caused by: java.lang.ArrayIndexOutOfBoundsException: Index 2 out of bounds for length 2

Using them individually is not an issue, and combining lowpass/timescale with other filters is also not an issue.

for further info & logs see: https://github.com/freyacodes/Lavalink/issues/491

**Comment by topi314** [comment]
this was an error in lavalink and has been fixed in https://github.com/freyacodes/Lavalink/pull/572
